Relicense signing Shourrya Guha
chrysalis-blc/.github pull request #2
Opened 2022-01-31 01:47 UTC by ShourryaGuha

Discord: Shourrya#2094
Email: guhashourrya@gmail.com

2022-01-31 02:48 UTC, hzhou0 requested changes
Just remove these two lines

2022-01-31 02:48 UTC, hzhou0 commented on RELICENSE/ShourryaGuha.md
> +```md
```suggestion

2022-01-31 02:48 UTC, hzhou0 commented on RELICENSE/ShourryaGuha.md
> +```
```suggestion
```
```

2022-02-01 15:06 UTC, merged

2022-02-01 15:07 UTC, ShourryaGuha commented
Done with the changes